apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: discord-bot-acts-as-riccardo-job
  # cloud-run-job-name # this job will be created in Cloud Run via Skaffold
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    spec:
      template:
        spec:
          containers:
          - image: us-docker.pkg.dev/cloudrun/container/job
